In [1]:
import numpy as np

### Task #1: Create a one-dimensional array (vector) with the first 10 natural numbers and print its values.

In [2]:
array = np.arange(1, 11)
print(f"Vector with the first 10 natural numbers: {array}")

Vector with the first 10 natural numbers: [ 1  2  3  4  5  6  7  8  9 10]


### Task #2: Create a two-dimensional array (matrix) of size 3x3, fill it with zeros, and print its values.

In [3]:
array = np.zeros((3,3))
print(f"Zero matrix:\n{array}")

Zero matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Task #3: Create an array of size 5x5, fill it with random integers in the range from 1 to 10, and print its values.

In [4]:
array = np.random.randint(1, 10, size=(5, 5))
print(f"An array of 5x5 random numbers from 1 to 10:\n{array}")

An array of 5x5 random numbers from 1 to 10:
[[4 9 7 1 1]
 [7 3 3 3 4]
 [7 1 9 9 5]
 [1 6 9 3 2]
 [7 7 5 3 3]]


### Task #4: Create an array of size 4x4, fill it with random floating-point numbers in the range from 0 to 1, and print its values.

In [5]:
array = np.random.random((4, 4))
print(f"An array of 4x4 random numbers from 0 to 1:\n{array}")

An array of 4x4 random numbers from 0 to 1:
[[0.78086311 0.67848106 0.332387   0.34415916]
 [0.94302777 0.47138089 0.15579405 0.77700209]
 [0.69013319 0.41196484 0.38518301 0.49813574]
 [0.25380392 0.92059978 0.64783405 0.76908766]]


### Task #5: Create two one-dimensional arrays of size 5, fill them with random integers in the range from 1 to 10, and perform element-wise addition, subtraction, and multiplication on them.

In [6]:
array_1 = np.random.randint(1, 10, size=5)
array_2 = np.random.randint(1, 10, size=5)

add_array = array_1 + array_2
sub_array = array_1 - array_2
mul_array = array_1 * array_2

print(f"First array: {array_1}\nSecond array: {array_2}\n\
Addition: {add_array}\nSubtraction: {sub_array}\n\
Multiplication: {mul_array}")

First array: [3 1 9 6 8]
Second array: [1 5 4 8 5]
Addition: [ 4  6 13 14 13]
Subtraction: [ 2 -4  5 -2  3]
Multiplication: [ 3  5 36 48 40]


### Task #6: Create two vectors of size 7, fill them with arbitrary numbers, and find their dot product.

In [7]:
vector_1 = np.random.randint(0, 10, size=7)
vector_2 = np.random.randint(0, 10, size=7)

dot_product = np.dot(vector_1, vector_2)

print(f"First vector: {vector_1}\nSecond vector: {vector_2}\nDot product: {dot_product}")

First vector: [1 7 9 2 4 5 6]
Second vector: [0 9 4 3 5 4 5]
Dot product: 175


### Task #7: Create two matrices of sizes 2x2 and 2x3, fill them with random integers in the range from 1 to 10, and multiply them together.

In [8]:
array_1 = np.random.randint(1, 10, size=(2, 2))
array_2 = np.random.randint(1, 10, size=(2, 3))

mult_array = np.dot(array_1, array_2)

print(f"First array:\n{array_1}\nSecond array:\n{array_2}\nMultiplication:\n{mult_array}")

First array:
[[2 9]
 [9 8]]
Second array:
[[5 4 6]
 [6 1 3]]
Multiplication:
[[64 17 39]
 [93 44 78]]


### Task #8: Create a matrix of size 3x3, fill it with random integers in the range from 1 to 10, and find its inverse matrix.

In [9]:
array = np.random.randint(1, 10, size=(3, 3))

array_inv = np.linalg.inv(array)

print(f"Array:\n{array}\nInverse matrix:\n{array_inv}")

Array:
[[3 1 1]
 [5 4 7]
 [5 2 8]]
Inverse matrix:
[[ 0.46153846 -0.15384615  0.07692308]
 [-0.12820513  0.48717949 -0.41025641]
 [-0.25641026 -0.02564103  0.17948718]]


### Task #9: Create a matrix of size 4x4, fill it with random floating-point numbers in the range from 0 to 1, and transpose it.

In [10]:
array = np.random.random((4, 4))

print(f"Array:\n{array}\nTranspose array:\n{array.T}")

Array:
[[0.40013393 0.17291138 0.16405078 0.39154941]
 [0.42800305 0.65721444 0.12530371 0.20845297]
 [0.67295341 0.31416412 0.00734399 0.5520248 ]
 [0.12879555 0.60241815 0.39122363 0.03628238]]
Transpose array:
[[0.40013393 0.42800305 0.67295341 0.12879555]
 [0.17291138 0.65721444 0.31416412 0.60241815]
 [0.16405078 0.12530371 0.00734399 0.39122363]
 [0.39154941 0.20845297 0.5520248  0.03628238]]


### Task #10: Create a matrix of size 3x4 and a vector of size 4, fill them with random integers in the range from 1 to 10, and multiply the matrix by the vector.

In [11]:
array = np.random.randint(1, 10, size=(3, 4))
vector = np.random.randint(1, 10, size=4)

mult_array = np.dot(array, vector)

print(f"Array:\n{array}\nVector:\n{vector}\nMultiplication:\n{mult_array}")

Array:
[[9 3 1 4]
 [9 6 3 4]
 [3 9 8 7]]
Vector:
[4 5 9 9]
Multiplication:
[ 96 129 192]


### Task #11: Create a matrix of size 2x3 and a vector of size 3, fill them with random floating-point numbers in the range from 0 to 1, and multiply the matrix by the vector.

In [12]:
array = np.random.random((2, 3))
vector = np.random.random(3)

mult_array = np.dot(array, vector)

print(f"Array:\n{array}\nVector:\n{vector}\nMultiplication:\n{mult_array}")

Array:
[[0.93367934 0.4674106  0.18357461]
 [0.92128655 0.59936056 0.1772094 ]]
Vector:
[0.83537475 0.44750342 0.75981384]
Multiplication:
[1.12862251 1.17248157]


### Task #12: Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10, and perform element-wise multiplication on them.

In [13]:
array_1 = np.random.randint(1, 10, size=(2, 2))
array_2 = np.random.randint(1, 10, size=(2, 2))

print(f"First array:\n{array_1}\nSecond array:\n{array_2}\nMultiplication by elements:\n{array_1 * array_2}")

First array:
[[7 6]
 [2 8]]
Second array:
[[8 8]
 [4 9]]
Multiplication by elements:
[[56 48]
 [ 8 72]]


### Task #13: Create two matrices of size 2x2, fill them with random integers in the range from 1 to 10, and find their product.

In [14]:
array_1 = np.random.randint(1, 10, size=(2, 2))
array_2 = np.random.randint(1, 10, size=(2, 2))

mult_array = np.dot(array_1, array_2)

print(f"First array:\n{array_1}\nSecond array:\n{array_2}\nMultiplication:\n{mult_array}")

First array:
[[2 4]
 [3 3]]
Second array:
[[8 7]
 [3 2]]
Multiplication:
[[28 22]
 [33 27]]


### Task #14: Create a matrix of size 5x5, fill it with random integers in the range from 1 to 100, and find the sum of the elements in the matrix.

In [15]:
array = np.random.randint(1, 100, size=(5, 5))

print(f"Array:\n{array}\nSum:\n{array.sum()}")

Array:
[[38 59 14 74 65]
 [39 91  2 99 55]
 [63 38  1 29 80]
 [46 22 91 12 38]
 [45 89 18 15 49]]
Sum:
1172


### Task #15: Create two matrices of size 4x4, fill them with random integers in the range from 1 to 10, and find their difference.

In [16]:
array_1 = np.random.randint(1, 10, size=(4, 4))
array_2 = np.random.randint(1, 10, size=(4, 4))

difference = array_1 - array_2

print(f"First array:\n{array_1}\nSecond array:\n{array_2}\nDifference:\n{difference}")

First array:
[[8 4 6 5]
 [9 3 2 7]
 [5 3 1 6]
 [5 3 9 3]]
Second array:
[[1 2 6 6]
 [3 6 5 2]
 [1 4 9 4]
 [1 9 4 9]]
Difference:
[[ 7  2  0 -1]
 [ 6 -3 -3  5]
 [ 4 -1 -8  2]
 [ 4 -6  5 -6]]


### Task #16: Create a matrix of size 3x3, fill it with random floating-point numbers in the range from 0 to 1, and find a column vector containing the sum of the elements in each row of the matrix.

In [17]:
array = np.random.random((3,3))

column_sums = np.sum(array, axis = 1)

print(f"Array:\n{array}\nСolumn where the sum of the elements of each row of the array:{column_sums}") 

Array:
[[0.00516302 0.35001112 0.14263538]
 [0.36441917 0.55810541 0.29486501]
 [0.17146258 0.70578149 0.6904827 ]]
Сolumn where the sum of the elements of each row of the array:[0.49780952 1.2173896  1.56772677]


### Task #17: Create a matrix of size 3x4 with arbitrary integers and create a matrix containing the squares of these numbers.

In [18]:
array = np.random.randint(1, 5, size=(3, 4))

squared_array = np.square(array)

print(f"Array:\n{array}\nSquared array:\n{squared_array}")

Array:
[[4 4 3 4]
 [3 1 3 3]
 [4 4 1 1]]
Squared array:
[[16 16  9 16]
 [ 9  1  9  9]
 [16 16  1  1]]


### Task #18: Create a vector of size 4, fill it with random integers in the range from 1 to 50, and find a vector containing the square roots of these numbers.

In [19]:
vector = np.random.randint(1, 50, size=4)

sqrt_vector = np.sqrt(vector)

print(f"Vector: {vector}\nVector with square roots of numbers: {sqrt_vector}")

Vector: [15 33 19  6]
Vector with square roots of numbers: [3.87298335 5.74456265 4.35889894 2.44948974]


### Task #19: Replace all odd numbers in arr with -1. `arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
print(f"Array: {arr}")

Array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Task #20: Create a 1D array and reshape it into a 2D array with 2 rows.

In [22]:
while True:
    n = np.random.randint(1, 10)
    if n % 2 == 0:
        break

one_demension = np.random.randint(1, 9, size=n)
two_demension = one_demension.reshape(2, -1)

print(f"One demension array:\n{one_demension}\nTwo demension array:\n{two_demension}")

One demension array:
[6 5 5 7]
Two demension array:
[[6 5]
 [5 7]]


### Task #21: Create two two-dimensional arrays, a and b, and stack them vertically.

In [23]:
a = np.random.randint(1, 9, size=(2, 2))
b = np.random.randint(1, 9, size=(2, 2))

vertical_folding = np.vstack((a, b))
print(f"Initial array a:\n{a}\nInitial array b:\n{b}\nThe result of vertical folding:\n{vertical_folding}")

Initial array a:
[[6 3]
 [4 2]]
Initial array b:
[[7 8]
 [1 1]]
The result of vertical folding:
[[6 3]
 [4 2]
 [7 8]
 [1 1]]


### Task #22: Create the following template without hard coding. Use only NumPy functions and the given input array.
Input: `a = np.array([1,2,3])`  
Output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

In [24]:
a = np.array([1,2,3])

repeat_a = np.repeat(a, 3)
tile_a = np.tile(a, 3)
result = np.concatenate((repeat_a, tile_a))

print(f"Input: {a}\n\
Output: {result}")

Input: [1 2 3]
Output: [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


### Task #23: Get the common elements between arrays a and b.

`a = np.array([1,2,3,2,3,4,3,4,5,6])`
`b = np.array([7,2,10,2,7,4,9,4,9,8])`

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_elements = np.intersect1d(a, b)
print(f"Common elements between a and b {common_elements}")

Common elements between a and b [2 4]


### Task #24: Get the indices of the first 5 maximum values in the given array a.

`np.random.seed(100)`
`a = np.random.uniform(1,50, 20)`

In [26]:
np.random.seed(100) 
a = np.random.uniform(1,50, 20)

sorted_indices = a.argsort()[::-1]
top_5_indices = sorted_indices[:5]

print(f"Array:\n{a}\n\
Top 5 indices: {top_5_indices}")

Array:
[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
Top 5 indices: [15 10  3  7 18]


### Task #25: Remove all NaN values from a one-dimensional array.
`а=np.array([1,2,3,np.nan,5,6,7,np.nan])`

In [27]:
a_array = np.array([1,2,3,np.nan,5,6,7,np.nan])

a_cleaned = a_array[~np.isnan(a_array)]

print(f"Cleaned array a_array {a_cleaned}")

Cleaned array a_array [1. 2. 3. 5. 6. 7.]


### Task #26: Calculate the Euclidean distance between two arrays, a and b.

`a = np.array([1,2,3,4,5])` `b = np.array([4,5,6,7,8])`

In [28]:
a = np.array([1,2,3,4,5]) 
b = np.array([4,5,6,7,8])

distance_1 = np.sqrt(sum((pow(b[i] - a[i], 2) for i in range(len(a)))))
distance_2 = np.linalg.norm(a - b)

print(f"The Euclidean distance between arrays a and b: {distance_1}\n\
The Euclidean distance between arrays a and b: {distance_2}")

The Euclidean distance between arrays a and b: 6.708203932499369
The Euclidean distance between arrays a and b: 6.708203932499369


### Task #27: Find the index of the 5th occurrence of the number 1 in the array x.

`x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])`

In [29]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

unique_values = np.unique(x)

for num in unique_values:
    indices = np.where(x == num)[0]
    if len(indices) > 4: 
        print(f"Number: {num}\nIndex of the 5th repetition: {indices[5]}")

Number: 1
Index of the 5th repetition: 10


### Task #28: Identify repeated entries in the given array and mark them as True, starting from the second occurrence. The first occurrence should be marked as False.

Input: `np.random.seed(100)` `a = np.random.randint(0, 5, 10)` `[0 0 3 0 2 4 2 2 2 2]`  
Output: `[False True False True False False True True True True]`

In [31]:
np.random.seed(100) 
a = np.random.randint(0, 5, 10)
unique_values = np.unique(a)

output = np.zeros_like(a, dtype=bool)

for num in unique_values:
    indices = np.where(a == num)[0]
    if len(indices) > 1:
        output[indices[1:]] = True
print(f"Input: {a}\nOutput: {output}")

Input: [0 0 3 0 2 4 2 2 2 2]
Output: [False  True False  True False False  True  True  True  True]
